[package]
name = "travel_office_server"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
chrono = "0.4.23"
postgres = "0.19"
serde_json = "1.0"
serde = { version = "1.0", features = ["derive"] }
